language: python
python: 2.7
sudo: required
services: docker
install: true

script: python setup.py sdist bdist_wheel

env:
  global:
    - IMAGE_NAME=gabrielegiammatteo/prometheus-openstack-exporter
    - REGISTRY_USER=gabrielegiammatteo
    # REGISTRY_PASS=...
    - secure: trUUB49tDoK4zZi77A/jyu/EMUCGerlGq+tUlq3duTJWylVu3Vb3tSoiTFoxoSvjRAnUu+s2iTaWHvMvRFIueacRLt1vlvdHm6IA4IkaNajJWEUyV0fgQs3vX+V9Z6Z2IX6tGiEWwFDgwuSuFpJ+zG9/4qB8+Kd8SX3Ui8vue53LTnAgmQBsocVYlTQ80+SSY2xIkqAYS5Af0ojWfS0ipGWNpRL8SkVae32zOZ6lpkNMTDnnMZp3wO4Sm465f84JL/KzxlqR9Se8ALY+SI3bkzRhTKUbwUCyYOdobXgDnsO3m/C2a3EttzQvxuzByHuBphQhhyN5FUBSnexsVlV1LMa5ZcP2IUb9yj2C4FN2PYaSqlnM23wdno1UkAHESlZJSXfzVBTyGYcwYTZ74Ez9Ab1ExYJoVjNOIQp3mbQd2Q59turmyQ4UGDy4IisKXtIcqRh5NswE75kEo/zRDvpiZzbtWhq7HW9gEx3SHM/sWzHYdJKzoSU2nG1i2Zazm129Pu1yqce73AmICCu/zK8cDqdJ998qiiAXtUsCsG/eOuXXettC0YV/dP1EF3mlfvD7c6XuKaW+EMwHN6NudR2yemtdCBDiROn8PMzMRZbF/WHRARZWVlUTpvwLpk7MGdtQEJl+mYY0sxgIKmDOcCmhoJCKLWSzraZlBs6fXlDVVL4=

before_deploy:
  - version=$(sed -nE "s/version='(.*)'.*/\1/p" setup.py | tr -d '[:space:]')
  - docker pull "${IMAGE_NAME}:develop" || true
  - docker build --pull --cache-from "${IMAGE_NAME}:develop" --tag "$IMAGE_NAME" .
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:develop"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"

deploy:

  # publish Docker development image
  - provider: script
    script: docker push "${IMAGE_NAME}:develop"
    on:
      all_branches: true

  # publish Docker release image if it is a tag commit
  #- provider: script
  #  script: docker push "${IMAGE_NAME}:${version}"
  #  on:
  #    tags: true

  # publish artifact on PYPITest
  #- provider: pypi
  #  server: https://test.pypi.org/legacy/
  #  user: testing.gabriele.giammatteo
  #  password:
  #    secure: T1ISjTJYedUw+NW3WXmgzehFH6TzEJrhuWnDqGDbbLz9TUo9phK+SGO74+O32KonGKqdv8JXttrGFZoY4N2W5QUVKWL7lDUoQaUsjFnKEN4qtSsWN7jcocKEEJzSrxAtG8m7btKKXowBxEGn2980OtBTVz+Ts/5RzPrtGRavoVj3VRjhuhn8wu1gKdw8/fe8ipb3LSveeSQMsU5IOsw2xG+NzebTmx3XS/RHcQSmsUnTeTIzgW+dUnUr7TJ5RamICOiUav73S7LBUH7P4pqdu2eFCBFGM8nc0lKB0ET9tKXS01FP9PXCKEG7duWizkEoYKhPp6+41GJyY29fQQQiNT87VzRqnQPS56tEUOns9uxzU9l4r+/lEf532qMJltXkxgXlUMIsMi42vxkJYa1XziehEzZ7gJCckNeko7dDWiwwOmYVhdp1HwWbmlDUmh3XoHzjdilWwI2fnBzqbHQohgpEin1A8HW47e8ZLUPb1FcpFTIolatzwYT992UkRrPUoVPF76a0kkIfREmNvq/QXYt1AXu/25FgHhZscGSm441DdWJCIuWjnmFy2SU0CGvuiZYRTmKWD9JCxOW3zWGNpJUPSyf+UVJBG6s/iFhtk/LhJ3eAF2blrpIlapMunfHZ1knLu5GGr4IA9UspcKIBotwugSCv4NfFMayojHFhhQM=
  #  distributions: sdist bdist_wheel
  #  skip_existing: true
  #  on:
  #    all_branches: true

  # publish artifact on PYPI if it is a tag commit
  #- provider: pypi
  #  user: gabriele.giammatteo
  #  password:
  #    secure: lCa/+znkyXsuKYFrzKPE/xZOmH1KgxDGF6iXmtT1xC3Jy5uovqN+r/dxZQlSmsp17a+EgFBesIv1R0QXN2AMDtYS1NxqrRpbqSscKX35UedpU62yNeClUjL4tcD+jWL16sHwiJ7l+GEdqUQ00r5LrWQfqjNPRyJ6CQSd9AgCBsL0xIw3orTSfC/L9LA7fxBVM9l3OSm1X4e9n6D6aP12jjpmE9qb3RISoqgYb+iGAxhlJM7lq2LO9PGt+JS2u+8nlh9kS7LU9OxDZCrL1FYesfESrXs/7qmHAqOVvWr/8Y9gmTFUpMKTDA58f861tt0Ed5rTnQ8DGORcK4ZAyT/LbV1LALxGQPuY/ZzoACtN/RhaHXwXhYlSiH8/ud0tvKe5wyhHHT9HScjm8dQEhTUMycJsBrj63m6OCUZt7toenE5wdkMainpVuHuXsFkkR/DqoAtUXcVkAeUHnHbLy62Brs1sMFKItOSdZ4BXS8jytsq9HupSC6HWa9qGr3EzPJ2S7NbF6e/AEvLc5TAe0WjxQ3POb567wKR/ZoATORVsoqzjhpgxA8IaDhnCjHTWNXlA+uZAUggjeXOTpI1UErJLCJi4s9/5k1IeQOrfJBeOXSSgqx4cd4bsNbgWEWE6sRdT7CwqdBJ64VAko85X7ltYLu/jkjV0FU2j0kltK5aihe0=
  #  distributions: sdist bdist_wheel
  #  skip_existing: true
  #  on:
  #    tags: true
